# Generated by Django 3.2.5 on 2021-11-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='school_website',
            field=models.URLField(blank=True, max_length=264, unique=True),
        ),
    ]
