# Generated by Django 3.2.5 on 2021-11-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_school_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='eigth',
            new_name='eighth',
        ),
    ]
