# Generated by Django 3.2.5 on 2021-11-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_rename_eigth_student_eighth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='school_website',
            field=models.URLField(blank=True, max_length=264),
        ),
    ]
