# Generated by Django 3.2.5 on 2021-11-17 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0009_school_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
